version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: miniapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6
    container_name: mongodb_container
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
